### ISSUE TITLE
Error writing the report

### ISSUE THREAD

**Issue by micafer** [EOSC-synergy/sqaaas-assessment-action#17]
Hi,

I get this error

```py
Traceback (most recent call last):
  File "/usr/bin/assess.py", line 313, in <module>
    main()
  File "/usr/bin/assess.py", line 305, in main
    summary = write_summary(sqaaas_report_json)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/assess.py", line 232, in write_summary
    summary = get_summary(sqaaas_report_json)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/assess.py", line 182, in get_summary
    repo = os.path.basename(repo_data['name']) # just need the last part
```

You can see the full log here: https://github.com/grycap/im/actions/runs/8077512920/job/22067945625?pr=1536#step:3:108 

When trying to add this action to my repo.
This is the GitHub actions file:

https://github.com/grycap/im/blob/sqa/.github/workflows/sqaaas.yaml

In fact, the error seems to be that the repository field of the returned JSON is a list with 1 element instead of a dict (as expected by the action code).
Could you take a look?

**Comment by orviz** [comment]
Hi @micafer thanks for reporting. The issue has been fixed in `2.3.0` and (updated) `v2`. Please reopen if the problem persists
